### PR TITLE
Makes id optional to request info.get()

### PR DESCRIPTION
**Pull request by Seraf**

### CODE REVIEW

**Comment by kstaniek** [comment]
I think it should be done by overriding the get method in weather, info and login controllers. I would try to keep 'get' for the other controllers with enforced 'id' as a mandatory argument to differentiate it from 'list' method (will even make it stronger by checking whether id is not None). In HC2 REST request (i.e. scenes, devices) the details in the output for each elements requested by /api/scenes or /api/devices are different than when you request the specific id. I'm not sure I'm clear now, but 'get' should always be a request for specific id. What do you think?

**Comment by Seraf** [comment]
I don't know.
For me overriding should take something generic to specialize it.
So it should be the inverse : having something generic without fields mandatory, and override to require the id.
Or, use two different methods ?

Anyway, it's up to you, I have no preference :)

**Comment by kstaniek** [comment]
Thanks for you comment. Will fix it somehow because so so far it seems to
be a bug, however still can use get(None) which seems to be a bit weird.

**Comment by Seraf** [comment]
Yes, I did the fix on the class on my PR to have something clear on the
README page (as the only one example on the README is broken ^^)

On Mon, Jun 9, 2014 at 9:57 AM, Klaudiusz Staniek notifications@github.com
wrote:

> Thanks for you comment. Will fix it somehow because so so far it seems to
> be a bug, however still can use get(None) which seems to be a bit weird.
> 
> On Mon, Jun 9, 2014 at 9:27 AM, Julien Syx notifications@github.com
> wrote:
> 
> > I don't know.
> > For me overriding should take something generic to specialize it.
> > So it should be the inverse : having something generic without fields
> > mandatory, and override to require the id.
> > Or, use two different methods ?
> > 
> > Anyway, it's up to you, I have no preference :)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/kstaniek/fiblary/pull/2#issuecomment-45467430.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kstaniek/fiblary/pull/2#issuecomment-45468950.

## 

Julien Syx
Ingénieur Systèmes & Réseaux

**Comment by kstaniek** [comment]
Fixed in 0.1.3

**Pull request closed without merging**
